# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7k160tffg676-2L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/panic/new/lab5/05_03/naive_pipeline_full/naive_pipeline_full.cache/wt [current_project]
set_property parent.project_path C:/panic/new/lab5/05_03/naive_pipeline_full/naive_pipeline_full.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths c:/panic/new/lab5/05_03/naive_pipeline_full/IP [current_project]
set_property ip_output_repo c:/panic/new/lab5/05_03/naive_pipeline_full/naive_pipeline_full.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files C:/panic/new/lab5/05_04/pipeline_stall/pipeline_stall.srcs/sources_1/imports/OExp02-IP2SOC/I_mem.coe
add_files C:/panic/new/lab5/05_04/pipeline_stall/pipeline_stall.srcs/sources_1/imports/OExp02-IP2SOC/D_mem.coe
add_files C:/panic/new/lab5/05_04/pipeline_stall/pipeline_stall.srcs/sources_1/bd/CSSTE/ip/CSSTE_RAM_B_0_0/RAM_B.srcs/D_mem.coe
add_files C:/panic/new/lab5/05_04/pipeline_stall/pipeline_stall.srcs/sources_1/imports/OExp02-IP2SOC/I_mem_Int.coe
add_files C:/panic/new/lab5/05_03/naive_pipeline_full/instruction.coe
add_files c:/panic/new/lab5/05_04/pipeline_stall/instruction.coe
read_mem {
  C:/panic/new/lab5/05_04/pipeline_stall/pipeline_stall.srcs/sources_1/imports/OExp02-IP2SOC/vga_debugger.mem
  C:/panic/new/lab5/05_04/pipeline_stall/pipeline_stall.srcs/sources_1/imports/OExp02-IP2SOC/font_8x16.mem
}
read_verilog -library xil_defaultlib C:/panic/new/lab5/05_04/pipeline_stall/pipeline_stall.srcs/sources_1/bd/CSSTE/hdl/CSSTE_wrapper.v
add_files C:/panic/new/lab5/05_04/pipeline_stall/pipeline_stall.srcs/sources_1/bd/CSSTE/CSSTE.bd
set_property used_in_implementation false [get_files -all c:/panic/new/lab5/05_04/pipeline_stall/pipeline_stall.srcs/sources_1/bd/CSSTE/ip/CSSTE_dist_mem_gen_0_0/CSSTE_dist_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/panic/new/lab5/05_04/pipeline_stall/pipeline_stall.srcs/sources_1/bd/CSSTE/ip/CSSTE_RAM_B_0_0/RAM_B.srcs/sources_1/ip/RAM/RAM_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/panic/new/lab5/05_04/pipeline_stall/pipeline_stall.srcs/sources_1/bd/CSSTE/CSSTE_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/panic/new/lab5/05_04/pipeline_stall/pipeline_stall.srcs/constrs_1/imports/CO/Org-Sword.xdc
set_property used_in_implementation false [get_files C:/panic/new/lab5/05_04/pipeline_stall/pipeline_stall.srcs/constrs_1/imports/CO/Org-Sword.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top CSSTE_wrapper -part xc7k160tffg676-2L


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef CSSTE_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file CSSTE_wrapper_utilization_synth.rpt -pb CSSTE_wrapper_utilization_synth.pb"
