# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7k160tffg676-2L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/panic/new/lab5/05_04/pipeline_stall/IP/CPU/CPU.cache/wt [current_project]
set_property parent.project_path C:/panic/new/lab5/05_04/pipeline_stall/IP/CPU/CPU.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths c:/panic/new/lab5/05_04/pipeline_stall/IP/CPU/CPU.srcs/sources_1/imports/pipeline_full [current_project]
set_property ip_output_repo c:/panic/new/lab5/05_04/pipeline_stall/IP/CPU/CPU.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog C:/panic/new/lab5/05_04/pipeline_stall/IP/CPU/CPU.srcs/sources_1/imports/pipeline_full/define.vh
read_verilog -library xil_defaultlib {
  C:/panic/new/lab5/05_04/pipeline_stall/IP/CPU/CPU.srcs/sources_1/imports/pipeline_full/EXE_reg_MEM.v
  C:/panic/new/lab5/05_04/pipeline_stall/IP/CPU/CPU.srcs/sources_1/imports/pipeline_full/ID_reg_EXE.v
  C:/panic/new/lab5/05_04/pipeline_stall/IP/CPU/CPU.srcs/sources_1/imports/pipeline_full/IF_reg_ID.v
  C:/panic/new/lab5/05_04/pipeline_stall/IP/CPU/CPU.srcs/sources_1/imports/pipeline_full/MEM_reg_WB.v
  C:/panic/new/lab5/05_04/pipeline_stall/IP/CPU/CPU.srcs/sources_1/imports/pipeline_full/controller.v
  C:/panic/new/lab5/05_04/pipeline_stall/IP/CPU/CPU.srcs/sources_1/imports/pipeline_full/execution.v
  C:/panic/new/lab5/05_04/pipeline_stall/IP/CPU/CPU.srcs/sources_1/imports/pipeline_full/immediate_generator.v
  C:/panic/new/lab5/05_04/pipeline_stall/IP/CPU/CPU.srcs/sources_1/imports/pipeline_full/registers.v
  C:/panic/new/lab5/05_04/pipeline_stall/IP/CPU/CPU.srcs/sources_1/imports/pipeline_full/instruction_decoder.v
  C:/panic/new/lab5/05_04/pipeline_stall/IP/CPU/CPU.srcs/sources_1/imports/pipeline_full/instruction_fetch.v
  C:/panic/new/lab5/05_04/pipeline_stall/IP/CPU/CPU.srcs/sources_1/imports/pipeline_full/memory_access.v
  C:/panic/new/lab5/05_04/pipeline_stall/IP/CPU/CPU.srcs/sources_1/imports/pipeline_full/stall_controller.v
  C:/panic/new/lab5/05_04/pipeline_stall/IP/CPU/CPU.srcs/sources_1/imports/pipeline_full/write_back.v
  C:/panic/new/lab5/05_04/pipeline_stall/IP/CPU/CPU.srcs/sources_1/imports/pipeline_full/pipeline_CPU.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}

synth_design -top pipeline_CPU -part xc7k160tffg676-2L


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef pipeline_CPU.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file pipeline_CPU_utilization_synth.rpt -pb pipeline_CPU_utilization_synth.pb"
