# 
# Report generation script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
proc start_step { step } {
  set stopFile ".stop.rst"
  if {[file isfile .stop.rst]} {
    puts ""
    puts "*** Halting run - EA reset detected ***"
    puts ""
    puts ""
    return -code error
  }
  set beginFile ".$step.begin.rst"
  set platform "$::tcl_platform(platform)"
  set user "$::tcl_platform(user)"
  set pid [pid]
  set host ""
  if { [string equal $platform unix] } {
    if { [info exist ::env(HOSTNAME)] } {
      set host $::env(HOSTNAME)
    }
  } else {
    if { [info exist ::env(COMPUTERNAME)] } {
      set host $::env(COMPUTERNAME)
    }
  }
  set ch [open $beginFile w]
  puts $ch "<?xml version=\"1.0\"?>"
  puts $ch "<ProcessHandle Version=\"1\" Minor=\"0\">"
  puts $ch "    <Process Command=\".planAhead.\" Owner=\"$user\" Host=\"$host\" Pid=\"$pid\">"
  puts $ch "    </Process>"
  puts $ch "</ProcessHandle>"
  close $ch
}

proc end_step { step } {
  set endFile ".$step.end.rst"
  set ch [open $endFile w]
  close $ch
}

proc step_failed { step } {
  set endFile ".$step.error.rst"
  set ch [open $endFile w]
  close $ch
}


start_step init_design
set ACTIVE_STEP init_design
set rc [catch {
  create_msg_db init_design.pb
  set_param xicom.use_bs_reader 1
  create_project -in_memory -part xc7k160tffg676-2L
  set_property design_mode GateLvl [current_fileset]
  set_param project.singleFileAddWarning.threshold 0
  set_property webtalk.parent_dir C:/panic/new/lab5/05_03/naive_pipeline_full/naive_pipeline_full.cache/wt [current_project]
  set_property parent.project_path C:/panic/new/lab5/05_03/naive_pipeline_full/naive_pipeline_full.xpr [current_project]
  set_property ip_repo_paths C:/panic/new/lab5/05_03/naive_pipeline_full/IP [current_project]
  set_property ip_output_repo C:/panic/new/lab5/05_03/naive_pipeline_full/naive_pipeline_full.cache/ip [current_project]
  set_property ip_cache_permissions {read write} [current_project]
  set_property XPM_LIBRARIES XPM_MEMORY [current_project]
  add_files -quiet C:/panic/new/lab5/05_03/naive_pipeline_full/naive_pipeline_full.runs/synth_1/CSSTE_wrapper.dcp
  set_msg_config -source 4 -id {BD 41-1661} -limit 0
  set_param project.isImplRun true
  add_files C:/panic/new/lab5/05_04/pipeline_stall/pipeline_stall.srcs/sources_1/bd/CSSTE/CSSTE.bd
  set_param project.isImplRun false
  read_edif c:/panic/new/lab5/05_04/pipeline_stall/pipeline_stall.srcs/sources_1/bd/CSSTE/ip/CSSTE_SAnti_jitter_0_0/SAnti_jitter.edf
  read_edif c:/panic/new/lab5/05_04/pipeline_stall/pipeline_stall.srcs/sources_1/bd/CSSTE/ip/CSSTE_Counter_x_0_0/Counter_x.edf
  read_edif c:/panic/new/lab5/05_04/pipeline_stall/pipeline_stall.srcs/sources_1/bd/CSSTE/ip/CSSTE_MIO_BUS_0_0/MIO_BUS.edf
  read_edif c:/panic/new/lab5/05_04/pipeline_stall/pipeline_stall.srcs/sources_1/bd/CSSTE/ip/CSSTE_Multi_8CH32_0_0/Multi_8CH32.edf
  read_edif c:/panic/new/lab5/05_04/pipeline_stall/pipeline_stall.srcs/sources_1/bd/CSSTE/ip/CSSTE_SPIO_0_0/SPIO.edf
  read_xdc C:/panic/new/lab5/05_04/pipeline_stall/pipeline_stall.srcs/constrs_1/imports/CO/Org-Sword.xdc
  set_param project.isImplRun true
  link_design -top CSSTE_wrapper -part xc7k160tffg676-2L
  set_param project.isImplRun false
  write_hwdef -force -file CSSTE_wrapper.hwdef
  close_msg_db -file init_design.pb
} RESULT]
if {$rc} {
  step_failed init_design
  return -code error $RESULT
} else {
  end_step init_design
  unset ACTIVE_STEP 
}

start_step opt_design
set ACTIVE_STEP opt_design
set rc [catch {
  create_msg_db opt_design.pb
  opt_design 
  write_checkpoint -force CSSTE_wrapper_opt.dcp
  create_report "impl_1_opt_report_drc_0" "report_drc -file CSSTE_wrapper_drc_opted.rpt -pb CSSTE_wrapper_drc_opted.pb -rpx CSSTE_wrapper_drc_opted.rpx"
  close_msg_db -file opt_design.pb
} RESULT]
if {$rc} {
  step_failed opt_design
  return -code error $RESULT
} else {
  end_step opt_design
  unset ACTIVE_STEP 
}

start_step place_design
set ACTIVE_STEP place_design
set rc [catch {
  create_msg_db place_design.pb
  implement_debug_core 
  place_design 
  write_checkpoint -force CSSTE_wrapper_placed.dcp
  create_report "impl_1_place_report_io_0" "report_io -file CSSTE_wrapper_io_placed.rpt"
  create_report "impl_1_place_report_utilization_0" "report_utilization -file CSSTE_wrapper_utilization_placed.rpt -pb CSSTE_wrapper_utilization_placed.pb"
  create_report "impl_1_place_report_control_sets_0" "report_control_sets -verbose -file CSSTE_wrapper_control_sets_placed.rpt"
  close_msg_db -file place_design.pb
} RESULT]
if {$rc} {
  step_failed place_design
  return -code error $RESULT
} else {
  end_step place_design
  unset ACTIVE_STEP 
}

start_step route_design
set ACTIVE_STEP route_design
set rc [catch {
  create_msg_db route_design.pb
  route_design 
  write_checkpoint -force CSSTE_wrapper_routed.dcp
  create_report "impl_1_route_report_drc_0" "report_drc -file CSSTE_wrapper_drc_routed.rpt -pb CSSTE_wrapper_drc_routed.pb -rpx CSSTE_wrapper_drc_routed.rpx"
  create_report "impl_1_route_report_methodology_0" "report_methodology -file CSSTE_wrapper_methodology_drc_routed.rpt -pb CSSTE_wrapper_methodology_drc_routed.pb -rpx CSSTE_wrapper_methodology_drc_routed.rpx"
  create_report "impl_1_route_report_power_0" "report_power -file CSSTE_wrapper_power_routed.rpt -pb CSSTE_wrapper_power_summary_routed.pb -rpx CSSTE_wrapper_power_routed.rpx"
  create_report "impl_1_route_report_route_status_0" "report_route_status -file CSSTE_wrapper_route_status.rpt -pb CSSTE_wrapper_route_status.pb"
  create_report "impl_1_route_report_timing_summary_0" "report_timing_summary -max_paths 10 -file CSSTE_wrapper_timing_summary_routed.rpt -rpx CSSTE_wrapper_timing_summary_routed.rpx -warn_on_violation "
  create_report "impl_1_route_report_incremental_reuse_0" "report_incremental_reuse -file CSSTE_wrapper_incremental_reuse_routed.rpt"
  create_report "impl_1_route_report_clock_utilization_0" "report_clock_utilization -file CSSTE_wrapper_clock_utilization_routed.rpt"
  close_msg_db -file route_design.pb
} RESULT]
if {$rc} {
  write_checkpoint -force CSSTE_wrapper_routed_error.dcp
  step_failed route_design
  return -code error $RESULT
} else {
  end_step route_design
  unset ACTIVE_STEP 
}

start_step write_bitstream
set ACTIVE_STEP write_bitstream
set rc [catch {
  create_msg_db write_bitstream.pb
  set_property XPM_LIBRARIES XPM_MEMORY [current_project]
  catch { write_mem_info -force CSSTE_wrapper.mmi }
  write_bitstream -force CSSTE_wrapper.bit 
  catch { write_sysdef -hwdef CSSTE_wrapper.hwdef -bitfile CSSTE_wrapper.bit -meminfo CSSTE_wrapper.mmi -file CSSTE_wrapper.sysdef }
  catch {write_debug_probes -quiet -force CSSTE_wrapper}
  catch {file copy -force CSSTE_wrapper.ltx debug_nets.ltx}
  close_msg_db -file write_bitstream.pb
} RESULT]
if {$rc} {
  step_failed write_bitstream
  return -code error $RESULT
} else {
  end_step write_bitstream
  unset ACTIVE_STEP 
}

